### ISSUE TITLE
SmoothScroll & useLocomotive error

### ISSUE THREAD

**Issue by BayBreezy** [StevenJPx2/nugget#1] opened 2024-01-09 13:28 UTC
Hey @StevenJPx2 ,

I was using the module when I came across this issue.
When I try to use the `<SmoothScroll>` component or the `useLocomotive` composable, I get the error below:

`Failed to resolve import "locomotive-scroll" from "node_modules/@fdcn/nugget/dist/runtime/composables/use-locomotive/index.mjs?v=edb9f9ca". Does the file exist?`

<img width="1416" alt="Screenshot 2024-01-09 at 8 24 25 AM" src="https://github.com/StevenJPx2/nugget/assets/53905713/e46930b3-f275-4e15-9700-412f70fec158">

**Comment by StevenJPx2** [comment] 2024-01-09 14:45
You just need to install locomotive-scroll@beta 😊.

I did this because it does not need to be installed in the entire bundle if the person does not need locomotive scroll. 

I'll include it in the docs next time! 

By the way, [I've created  docs page, if you wanna check it out!](https://nugget.stevenjohn.co)

Still a MASSIVE WIP and is subject to change.

**Comment by BayBreezy** [comment] 2024-01-09 18:30
Awesome! Installing it did save the day. This has to be added to the docs.
I did see the link to the docs & I see where it is still being worked on. Docs really help users get up and runnign quickly with your module.


I was also having some issues with the gsap plugin registrations. I had to register the gsap modules manually even after passing them to the composable `useGsap`. Are you able to take a look at that?

**Comment by StevenJPx2** [comment] 2024-01-10 01:56
Can you tell me which ones so I can check it out? I personally only use ScrollTrigger, and I auto register that.

**Comment by StevenJPx2** [comment] 2024-01-15 13:07
Hey!

I'll close this if you don't have any reproductions, thanks!

**Closed as not planned by StevenJPx2** 2024-01-15 13:07 UTC
Labels: norepro

**Comment by BayBreezy** [comment] 2024-01-17 21:12
Sorry @StevenJPx2  for not getting back to you.
I was not able to reproduce the issue. I am however getting another warning 

```bash
 WARN  Duplicated imports "vAos", the one from ".../node_modules/@fdcn/nugget/dist/runtime/composables/directives.mjs" has been ignored and ".../node_modules/@fdcn/nugget/dist/runtime/composables/use-animate-on-scroll/directive.mjs" is used
```

**Comment by StevenJPx2** [comment] 2024-01-18 00:36
Hey Behon!

I’ll get that fixed soon… there’s another thing. I’ll also be deprecating `<SmoothScroll />` for `<Locomotive />`. This is to have a more consistent naming scheme against all the other components with their composable counterparts.

I’m moving all of them from separate folders (components, composables) to be in the same folder (functions).

**Comment by BayBreezy** [comment] 2024-01-18 01:15
Alright cool cool. Just mention me once it is updated. Thanks :)

**Comment by StevenJPx2** [comment] 2024-01-19 18:49
0.3 is pushed! Check it out!

**Comment by BayBreezy** [comment] 2024-01-20 11:31
@StevenJPx2 Now, I get this error
```bash
Pre-transform error: Failed to resolve import ".../node_modules/@fdcn/nugget/dist/functions/plugin" from "virtual:nuxt:/.../.nuxt/plugins/client.mjs". Does the file exist?
```

And then the client shows this error

<img width="1416" alt="image" src="https://github.com/StevenJPx2/nugget/assets/53905713/680b46cf-0116-4784-8bf3-e1ba50e5c78c">

**Comment by StevenJPx2** [comment] 2024-01-21 05:02
Thanks for raising this! If you can, please raise a new issue for this.
